general.import = ["/home/kartel/.cache/wal/colors-alacritty.toml"]
general.live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "alacritty"

[font]
builtin_box_drawing = true
size = 22.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "Y"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "W"
mods = "Alt"

[scrolling]
history = 100000
multiplier = 6

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
dynamic_title = true
opacity = 0.9
title = "Alacritty"
[window.padding]
x = 15
y = 15
